SequoiaApp/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from SequoiaApp import views
from SequoiaApp.views import RemitterUpdateView, CustomerUpdateView


urlpatterns = [
    # miscellaneous urls
    url(r'^$', views.home, name='home'),
    url(r'^disclaimer/$', views.disclaimer, name='disclaimer'),

    # remitter urls
    url(r'^remitter/create/$', views.remitter_create, name='remitter_create'),
    url(r'^remitter/$', views.remitter_search, name='remitter_search'),
    url(r'^remitter/(?P<pk>\d+)/update/$',
        login_required(RemitterUpdateView.as_view()), name='remitter_update'),
    url(r'^remitter/(?P<pk>\d+)/delete/$',
        views.remitter_delete, name='remitter_delete'),

    #customer urls
    url(r'^customer/create/$', views.customer_create, name='customer_create'),
    url(r'^customer/$', views.customer_search, name='customer_search'),
    url(r'^customer/(?P<pk>\d+)/update/$',
        login_required(CustomerUpdateView.as_view()), name='customer_update'),
    url(r'^customer/(?P<pk>\d+)/delete/$',
        views.customer_delete, name='customer_delete'),

    #rtgs urls
    url(r'^rtgs/create/$', views.rtgs_create, name='rtgs_create'),
    url(r'^rtgs/(?P<pk>\d+)/$', views.rtgs, name='rtgs'),
    url(r'^rtgs/$', views.rtgs_search, name='rtgs_search'),
    # TODO need a delete view for RTGS

    # ajax urls
    url(r'^ajax/customer/autocomplete/$', views.customer_autocomplete,
        name='customer-autocomplete'),
    url(r'ajax/customer/get-id/',
        views.customer_get_data, name='customer-get-data'),
]

SequoiaProject/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('SequoiaApp.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

SequoiaApp/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from .validators import validate_GSTIN, getCheckDigitOfGSTIN
from django.core.validators import RegexValidator

class Remitter(models.Model):
    name = models.CharField(max_length=256)
    account_number = models.CharField(max_length=256, blank=False)
    mobile_number = models.CharField(max_length=10, blank=False)
    PAN = models.CharField(max_length=10, blank=False, null=False)
    GSTIN = models.CharField(max_length=15, blank=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="Remitter", default=1)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("remitter_search")


class Customer(models.Model):
    name = models.CharField(max_length=256)
    bank_name = models.CharField(max_length=250, blank=False, null=False)
    bank_account_number = models.CharField(max_length=256, blank=False, null=False)
    bank_branch_name = models.CharField(max_length=256, blank=False, null=False)
    bank_ifsc_code = models.CharField(max_length=256, blank=False, null=False)
    PAN = models.CharField(max_length=10)
    mobile_number = models.CharField(max_length=10, blank=False, null=False)
    GSTIN = models.CharField(max_length=15, blank=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="Customer", default=1)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("customer_search")

class RTGS(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="RTGS")
    remitter = models.ForeignKey(Remitter, on_delete=models.CASCADE, related_name="RTGS")
    cheque_number = models.CharField(max_length=16, blank=False)
    amount_in_figure = models.DecimalField(max_digits=10, decimal_places=2)
    amount_in_word = models.CharField(max_length=1024, blank=False, null=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="RTGS", default=1)

    def __str__(self):
        return self.customer.name + " " + str(self.amount_in_figure)

    def __unicode__(self):
        return self.customer.name + " " + str(self.amount_in_figure)

    class Meta:
        verbose_name_plural = "RTGS"

SequoiaApp/forms.py
from django import forms
from .models import Customer, Remitter, RTGS

from .validators import validate_GSTIN, getCheckDigitOfGSTIN
from django.core.validators import RegexValidator

PAN_Validator = RegexValidator(
    r'[a-zA-Z]{5}\d{4}[a-zA-Z]$', "Please make sure you have entered correct PAN")
GSTIN_Validator = RegexValidator(
    r'\d{2}[a-zA-Z]{5}\d{4}[a-zA-Z]\d[zZ]\d', "Please make sure you have entered correct GSTIN")

class RTGSForm(forms.ModelForm):
    name = forms.CharField(max_length=256)
    bank_name = forms.CharField(max_length=256)
    bank_account_number = forms.CharField(
        max_length=256, required=True)
    bank_branch_name = forms.CharField(
        max_length=256, required=True)
    bank_ifsc_code = forms.CharField(max_length=256, required=True)
    PAN = forms.CharField(max_length=10, validators=[PAN_Validator])
    mobile_number = forms.CharField(max_length=10, required=True)
    GSTIN = forms.CharField(max_length=15, required=False, validators=[GSTIN_Validator])
    customer_id = forms.CharField()

    class Meta:
        model = RTGS
        fields = ['customer_id', 'remitter', 'cheque_number', 'amount_in_figure', 'amount_in_word', 'name',
                  'bank_name', 'bank_account_number', 'bank_branch_name', 'bank_ifsc_code', 'PAN', 'mobile_number', 'GSTIN']

    # def clean(self):
    #     cleaned_data = super(RTGSForm, self).clean()
    #     cheque_number = cleaned_data.get('cheque_number')
    #     amount_in_figure = cleaned_data.get('amount_in_figure')
    #     amount_in_word = cleaned_data.get('amount_in_word')
    #     bank_name = cleaned_data.get('bank_name')
    #     bank_account_number = cleaned_data.get('bank_account_number')
    #     bank_branch_name = cleaned_data.get('bank_branch_name')
    #     bank_ifsc_code = cleaned_data.get('bank_ifsc_code')
    #     PAN = cleaned_data.get('PAN')
    #     mobile_number = cleaned_data.get('mobile_number')
    #     GSTIN = cleaned_data.get('GSTIN')
    #     name = cleaned_data.get('name')

class RemitterForm(forms.ModelForm):
    PAN = forms.CharField(max_length=10, validators=[PAN_Validator])
    GSTIN = forms.CharField(max_length=15, validators=[GSTIN_Validator])
    class Meta:
        model = Remitter
        fields = ['name', 'account_number', 'mobile_number', 'PAN', 'GSTIN']

class CustomerForm(forms.ModelForm):
    PAN = forms.CharField(max_length=10, validators=[PAN_Validator])
    GSTIN = forms.CharField(max_length=15, validators=[GSTIN_Validator])
    class Meta:
        model = Customer
        fields = ['name', 'bank_name', 'bank_account_number', 'bank_branch_name', 'bank_ifsc_code', 'PAN', 'mobile_number', 'GSTIN']

SequoiaApp/views.py
"""
Importing reqiured packages
"""
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, HttpResponseRedirect, redirect, render, render_to_response, Http404
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from django.forms.models import model_to_dict

from .forms import RemitterForm, CustomerForm, RTGSForm
from .models import Remitter, Customer, RTGS
# Create your views here.

import json


@login_required
def home(request):
    """This is just a Home Page and login in required to access"""
    return render(request, 'SequoiaApp/home.html', context={'active_dashboard': 'active'})


def disclaimer(request):
    """
    This is disclaimer for the application
    """
    return render(request, 'disclaimer.html')


@login_required
def remitter_create(request):
    """This function is used to create Remitter"""
    form = RemitterForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            Remitter.objects.create(
                name=form.cleaned_data.get('name'),
                account_number=form.cleaned_data.get('account_number'),
                mobile_number=form.cleaned_data.get('mobile_number'),
                PAN=form.cleaned_data.get('PAN'),
                GSTIN=form.cleaned_data.get('GSTIN'),
                created_by=request.user
            )
            return HttpResponseRedirect(reverse(remitter_search))
    return render(request, 'SequoiaApp/remitter_create.html', {'form': form})


@login_required
def remitter_search(request):
    """This function is used to search Remitters"""
    user = request.user
    if user.is_superuser:
        remitter_list = Remitter.objects.all()
    else:
        remitter_list = Remitter.objects.filter(created_by=user)
    return render(request, 'SequoiaApp/remitter_search.html', {'filter': remitter_list})


@method_decorator(login_required, name='dispatch')
class RemitterUpdateView(UpdateView):
    """This function is used for Updating Remitter Data"""
    fields = ('name', 'account_number', 'mobile_number', 'PAN', 'GSTIN')
    model = Remitter

    def user_passes_test(self, request):
        if request.user.is_authenticated:
            self.object = self.get_object()
            return self.object.created_by == request.user
        else:
            return False

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return super(RemitterUpdateView, self).dispatch(request, *args, **kwargs)
        elif not self.user_passes_test(request):
            return redirect("remitter_search")
        return super(RemitterUpdateView, self).dispatch(request, *args, **kwargs)


@login_required
def remitter_delete(request, pk=None):
    """This function is used to delete Remitter"""
    remitter = get_object_or_404(Remitter, pk=pk)
    if request.user == remitter.created_by or request.user.is_superuser:
        remitter.delete()
        return redirect("remitter_search")
    else:
        return redirect("remitter_search")


@login_required
def customer_create(request):
    """This function is used to create Customer"""
    form = CustomerForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            Customer.objects.create(
                name=form.cleaned_data.get('name'),
                bank_name=form.cleaned_data.get('bank_name'),
                bank_account_number=form.cleaned_data.get(
                    'bank_account_number'),
                bank_branch_name=form.cleaned_data.get('bank_branch_name'),
                bank_ifsc_code=form.cleaned_data.get('bank_ifsc_code'),
                PAN=form.cleaned_data.get('PAN'),
                mobile_number=form.cleaned_data.get('mobile_number'),
                GSTIN=form.cleaned_data.get('GSTIN'),
                created_by=request.user
            )
            return HttpResponseRedirect(reverse(customer_search))
    return render(request, 'SequoiaApp/customer_create.html', {'form': form})


@login_required
def customer_search(request):
    """This function is used to search Customers"""
    user = request.user
    if user.is_superuser:
        customer_list = Customer.objects.all()
    else:
        customer_list = Customer.objects.filter(created_by=user)
    return render(request, 'SequoiaApp/customer_search.html', {'filter': customer_list})


@method_decorator(login_required, name='dispatch')
class CustomerUpdateView(UpdateView):
    """This function is used to Update Customer"""
    fields = ('name', 'bank_name', 'bank_account_number', 'bank_branch_name',
              'bank_ifsc_code', 'PAN', 'mobile_number', 'GSTIN')
    model = Customer

    def user_passes_test(self, request):
        if request.user.is_authenticated:
            self.object = self.get_object()
            return self.object.created_by == request.user
        else:
            return False

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return super(CustomerUpdateView, self).dispatch(request, *args, **kwargs)
        elif not self.user_passes_test(request):
            return redirect("remitter_search")
        return super(CustomerUpdateView, self).dispatch(request, *args, **kwargs)


@login_required
def customer_delete(request, pk=None):
    """This function is used to delete Customers"""
    customer = get_object_or_404(Customer, pk=pk)
    if request.user == customer.created_by or request.user.is_superuser:
        customer.delete()
        return redirect("customer_search")
    else:
        return redirect("customer_search")


@login_required
def rtgs_create(request):
    # get or create the form
    form = RTGSForm(request.POST or None)
    if form.is_valid():
        # Get the customer id (hidden field) from the form
        customer_id = form.cleaned_data.get('customer_id')
        try:
            # get the customer instance
            customer = Customer.objects.get(id=customer_id)
        except (Customer.DoesNotExist, ValueError):
            # else create a new one
            customer = Customer()

        # if anything has been changed: update it
        for key, value in form.cleaned_data.items():
            if key in vars(customer).keys():
                if (getattr(customer, key) == '' or getattr(customer, key) == None or getattr(customer, key) != value):
                    setattr(customer, key, value)
        
        # finally
        customer.created_by = request.user
        customer.save()

        # use the customer instance created above
        rtgs = RTGS.objects.create(
            customer=customer,
            remitter=form.cleaned_data.get('remitter'),
            cheque_number=form.cleaned_data.get('cheque_number'),
            amount_in_figure=form.cleaned_data.get('amount_in_figure'),
            amount_in_word=form.cleaned_data.get('amount_in_word'),
            created_by=request.user
        )

        # redirect to the RTGS view, so that when the user navigates back
        # the browser doesn't POST again
        return redirect("rtgs", pk=rtgs.pk)
    
    # fetch the remitters created by the current logged in user to display as dropdown in the RTGS create form
    remitters = Remitter.objects.filter(created_by=request.user)

    # also: activate the "Create RTGS" in the side bar
    return render(request, 'SequoiaApp/rtgs_create.html', {'form': form, 'remitters': remitters, 'active_create_rtgs': 'active'})


@login_required
def rtgs_form(request):
    return render(request, 'SequoiaApp/rtgs_form.html')


@login_required
def rtgs_search(request):
    user = request.user
    rtgs_list = RTGS.objects.filter(created_by=user)
    return render(request, 'SequoiaApp/rtgs_list.html', {'rtgs_list': rtgs_list})


@login_required
def rtgs(request, pk):
    rtgs = get_object_or_404(RTGS, pk=pk)
    if request.user == rtgs.created_by or request.user.is_superuser:
        return render(request, 'SequoiaApp/rtgs_form.html', {'rtgs': rtgs})
    else:
        return redirect("rtgs_search")


@login_required
def customer_autocomplete(request):
    # fetch all the customers from the DB
    qs = Customer.objects.all()

    # if not present: return with error and status 404
    if qs.count() == 0:
        return JsonResponse({'result': [], 'error': 'Customers not present.'}, status=404)

    # get the 'q' param from the request
    q = request.GET.get('q', None)
    # print('"GET /ajax/customer/autocomplete/" q {}'.format(q))

    # if present: filter the customer set and match the ones that start with the string in q
    if q != "" and q != None:
        qs = qs.filter(name__istartswith=q)

    # make it return dict containg name and id
    qs = qs.values('name', 'id')

    # iterate over the queryset and assign a name to each id
    result_list = {}
    for obj in qs:
        result_list[obj.get('id')] = obj.get('name')

    return JsonResponse({'result': result_list})


@login_required
def customer_get_data(request):
    if request.method == 'POST':
        try:
            # get the customer id from the POSt and cast it to an integer
            customer_id = int(request.POST.get('id', None))
            # print('"POST /ajax/customer/customer_get_data/" customer_id {}'.format(customer_id))
            # get the customer instance
            customer = Customer.objects.get(id=customer_id)

            # make an iterable with the customer instance above and serialize it
            customerJSON = serializers.serialize('json', [customer, ])

            # create a dictionary from the JSON object
            struct = json.loads(customerJSON)

            # assign the fields of the customer to the customerJSON
            # that is what we want
            customerJSON = struct[0]['fields']

templates/SequoiaApp/customer_create.html
{% extends "base.html" %}
{% block title %}
    Create Customer - {{ block.super }}
{% endblock title %}
{% block content %}
    <div class="container">
        <h1>Create Customer:</h1>
        <div class="jumbotron" style="padding-top:3%; padding-bottom:3%; margin-bottom:8%">
            <form method="POST" novalidate>
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-sm-12 col-md-12">
                        <label for="id_name">Name:</label>
                        {% if form.name.value %}
                        <input type="text" name="name" maxlength="256" value="{{form.name.value}}" class="form-control {% if form.name.errors %}is-invalid{% else%}is-valid{% endif %}"
                            required id="id_name" /> {% else %}
                        <input type="text" name="name" maxlength="256" class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                            required id="id_name" /> {% endif %}
                        <div class="invalid-feedback">{{ form.name.errors }}</div>
                    </div>
                    <div class="form-group col-sm-6 col-md-6">
                        <label for="id_bank_name">Bank name:</label>
                        {% if form.bank_name.value %}
                        <input type="text" name="bank_name" maxlength="256" value="{{form.bank_name.value}}" class="form-control {% if form.bank_name.errors %}is-invalid{% else%}is-valid{% endif %}"
                            required id="id_bank_name" /> {% else %}
                        <input type="text" name="bank_name" maxlength="256" class="form-control {% if form.bank_name.errors %}is-invalid{% endif %}"
                            required id="id_bank_name" /> {% endif %}
                        <div class="invalid-feedback">{{ form.bank_name.errors }}</div>
                    </div>
                    <div class="form-group col-sm-6 col-md-6">
                        <label for="id_bank_account_number">Bank account number:</label>
                        {% if form.bank_account_number.value %}
                        <input type="text" name="bank_account_number" maxlength="256" value="{{form.bank_account_number.value}}" class="form-control {% if form.bank_account_number.errors %}is-invalid{% else%}is-valid{% endif %}"
                            required id="id_bank_account_number" /> {% else %}
                        <input type="text" name="bank_account_number" maxlength="256" class="form-control {% if form.bank_account_number.errors %}is-invalid{% endif %}"
                            required id="id_bank_account_number" /> {% endif %}
                        <div class="invalid-feedback">{{ form.bank_account_number.errors }}</div>
                    </div>
                    <div class="form-group col-sm-6 col-md-6">
                        <label for="id_bank_branch_name">Bank branch name:</label>
                        {% if form.bank_branch_name.value %}
                        <input type="text" name="bank_branch_name" maxlength="256" value="{{form.bank_branch_name.value}}" class="form-control {% if form.bank_branch_name.errors %}is-invalid{% else%}is-valid{% endif %}"
                            required id="id_bank_branch_name" /> {% else %}
                        <input type="text" name="bank_branch_name" maxlength="256" class="form-control {%if form.bank_branch_name.errors %}is-invalid{% endif %}"
                            required id="id_bank_branch_name" /> {% endif %}
                        <div class="invalid-feedback">{{ form.bank_branch_name.errors }}</div>
                    </div>
                    <div class="form-group col-sm-6 col-md-6">
                        <label for="id_bank_ifsc_code">Bank ifsc code:</label>
                        {% if form.bank_ifsc_code.value %}
                        <input type="text" name="bank_ifsc_code" maxlength="256" value="{{form.bank_ifsc_code.value}}" class="form-control {% if form.bank_ifsc_code.errors %}is-invalid{% else%}is-valid{% endif %}"
                            required id="id_bank_ifsc_code" /> {% else %}
                        <input type="text" name="bank_ifsc_code" maxlength="256" class="form-control {% if form.bank_ifsc_code.errors %}is-invalid{% endif %}"
                            required id="id_bank_ifsc_code" /> {% endif %}
                        <div class="invalid-feedback">{{ form.bank_ifsc_code.errors }}</div>
                    </div>
                    <div class="form-group col-sm-12 col-md-12">
                        <label for="id_mobile_number">Mobile number:</label>
                        {% if form.mobile_number.value %}
                        <input type="text" name="mobile_number" maxlength="10" value="{{form.mobile_number.value}}" class="form-control {% if form.mobile_number.errors %}is-invalid{% else%}is-valid{% endif %}"
                        required id="id_mobile_number" /> {% else %}
                        <input type="text" name="mobile_number" maxlength="10" class="form-control {% if form.mobile_number.errors %}is-invalid{% endif %}"
                        required id="id_mobile_number" /> {% endif %}
                        <div class="invalid-feedback">{{ form.mobile_number.errors }}</div>
                    </div>
                    <div class="form-group col-sm-12 col-md-12">
                        <label for="id_PAN">PAN:</label>
                        {% if form.PAN.value %}
                        <input type="text" name="PAN" maxlength="10" value="{{form.PAN.value}}" class="form-control {% if form.PAN.errors %}is-invalid{% else %}is-valid{% endif %}"
                            required id="id_PAN" /> {% else %}
                        <input type="text" name="PAN" maxlength="10" class="form-control {% if form.PAN.errors %}is-invalid{% endif %}" required
                            id="id_PAN" /> {% endif %}
                        <div class="invalid-feedback">{{ form.PAN.errors }}</div>
                    </div>
                    <div class="form-group col-sm-12 col-md-12">
                        <label for="id_GSTIN">GSTIN:</label>
                        {% if form.GSTIN.value %}
                        <input type="text" name="GSTIN" maxlength="15" value="{{form.GSTIN.value}}" class="form-control {% if form.GSTIN.errors %}is-invalid{% else%}is-valid{% endif %}"
                            id="id_GSTIN" /> {% else %}
                        <input type="text" name="GSTIN" maxlength="15" class="form-control {% if form.GSTIN.errors %}is-invalid{% endif %}"
                            id="id_GSTIN" /> {% endif %}
                        <div class="invalid-feedback">{{ form.GSTIN.errors }}</div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Create</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/SequoiaApp/customer_form.html
{% extends "base.html" %}
{% block title %} Update Remitter - {{block.super}} {% endblock title %}
{% block content %}
<div class="container">
    <div class="jumbotron" style="padding-top:3%; padding-bottom:3%; margin-bottom:8%">
        <h1>Update Customer:</h1>
        <form method="POST">
            {% csrf_token %}
            {% include "includes/form.html" %}
            <button class="btn btn-primary" type="submit">Update</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/SequoiaApp/customer_search.html
{% extends "base.html" %}
{% block title %} Search Customer - {{ block.super }} {% endblock title %}
{% load widget_tweaks %}
{% block content %}
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Customer Data:</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Customer Name</th>
                        <th>Bank Name</th>
                        <th>Bank Account Number</th>
                        <th>PAN</th>
                        <th>Mobile Number</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Customer Name</th>
                        <th>Bank Name</th>
                        <th>Bank Account Number</th>
                        <th>PAN</th>
                        <th>Mobile Number</th>
                        <th>Actions</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for customer in filter %}
                    <tr>
                        <td>{{customer.name}}</td>
                        <td>{{customer.bank_name}}</td>
                        <td>{{customer.bank_account_number}}</td>
                        <td>{{customer.PAN}}</td>
                        <td>{{customer.mobile_number}}</td>
                        <td>
                            <a href="{% url 'customer_update' pk=customer.pk %}">
                                <i class="fa fa-fw fa-edit fa-lg"></i>
                            </a>
                            <a href="{% url 'customer_delete' pk=customer.pk %}">
                                <i class="fa fa-fw fa-trash fa-lg"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">No data</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/SequoiaApp/remitter_create.html
{% extends "base.html" %}
{% block title %}
    Create Remitter - {{block.super}}
{% endblock title %}
{% block content %}
<div class="container">
    <div class="jumbotron" style="padding-top:3%; padding-bottom:3%; margin-bottom:8%">
        <h1>Create Remitter:</h1>
            <form method="POST" novalidate>
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-sm-12 col-md-12">
                        <label for="id_name">Name:</label>
                        {% if form.name.value %}
                        <input type="text" name="name" maxlength="256" value="{{form.name.value}}" class="form-control {% if form.name.errors %}is-invalid{% else%}is-valid{% endif %}"
                            required id="id_name" /> {% else %}
                        <input type="text" name="name" maxlength="256" class="form-control {% if form.name.errors %}is-invalid{% endif %}" required
                            id="id_name" /> {% endif %}
                        <div class="invalid-feedback">{{ form.name.errors }}</div>
                    </div>
                    <div class="form-group col-sm-12 col-md-12">
                        <label for="id_account_number">Account number:</label>
                        {% if form.account_number.value %}
                        <input type="text" name="account_number" maxlength="256" value="{{form.account_number.value}}" class="form-control {% if form.account_number.errors %}is-invalid{% else%}is-valid{% endif %}"
                            required id="id_account_number" /> {% else %}
                        <input type="text" name="account_number" maxlength="256" class="form-control {% if form.account_number.errors %}is-invalid{% endif %}"
                            required id="id_account_number" /> {% endif %}
                        <div class="invalid-feedback">{{ form.account_number.errors }}</div>
                    </div>
                    <div class="form-group col-sm-12 col-md-12">
                        <label for="id_mobile_number">Mobile number:</label>
                        {% if form.mobile_number.value %}
                        <input type="text" name="mobile_number" maxlength="10" value="{{form.mobile_number.value}}" class="form-control {% if form.mobile_number.errors %}is-invalid{% else%}is-valid{% endif %}"
                            required id="id_mobile_number" /> {% else %}
                        <input type="text" name="mobile_number" maxlength="10" class="form-control {% if form.mobile_number.errors %}is-invalid{% endif %}"
                            required id="id_mobile_number" /> {% endif %}
                        <div class="invalid-feedback">{{ form.mobile_number.errors }}</div>
                    </div>
                    <div class="form-group col-sm-12 col-md-12">
                        <label for="id_PAN">PAN:</label>
                        {% if form.PAN.value %}
                        <input type="text" name="PAN" maxlength="10" value="{{form.PAN.value}}" class="form-control {% if form.PAN.errors %}is-invalid{% else%}is-valid{% endif %}"
                            required id="id_PAN" /> {% else %}
                        <input type="text" name="PAN" maxlength="10" class="form-control {% if form.PAN.errors %}is-invalid{% endif %}" required
                            id="id_PAN" /> {% endif %}
                        <div class="invalid-feedback">{{ form.PAN.errors }}</div>
                    </div>
                    <div class="form-group col-sm-12 col-md-12">
                        <label for="id_GSTIN">GSTIN:</label>
                        {% if form.GSTIN.value %}
                        <input type="text" name="GSTIN" maxlength="15" value="{{form.GSTIN.value}}" class="form-control {% if form.GSTIN.errors %}is-invalid{% else%}is-valid{% endif %}"
                            id="id_GSTIN" /> {% else %}
                        <input type="text" name="GSTIN" maxlength="15" class="form-control {% if form.GSTIN.errors %}is-invalid{% endif %}"
                            id="id_GSTIN" /> {% endif %}
                        <div class="invalid-feedback">{{ form.GSTIN.errors }}</div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Create</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/SequoiaApp/remitter_form.html
{% extends "base.html" %}
{% block title %} Update Remitter - {{block.super}} {% endblock title %}
{% block content %}
<div class="container">
    <div class="jumbotron" style="padding-top:3%; padding-bottom:3%; margin-bottom:8%">
        <h1>Update Remitter:</h1>
        <form method="POST">
            {% csrf_token %}
            {% include "includes/form.html" %}
            <button class="btn btn-primary" type="submit">Update</button>
        </form>
    </div>
</div>
{% endblock content %}